before:
  hooks:
    - go mod download
builds:
  - main: main.go
    binary: gotf
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - linux
      - darwin
      - windows
    ldflags:
      - >-
        -X github.com/craftypath/gotf/pkg/gotf.Version={{ .Tag }}
        -X github.com/craftypath/gotf/pkg/gotf.GitCommit={{ .Commit }}
        -X github.com/craftypath/gotf/pkg/gotf.BuildDate={{ .Date }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
brews:
  - github:
      owner: craftypath
      name: homebrew-tap
    commit_author:
      name: craftypath
      email: craftypath@users.noreply.github.com
    folder: Formula
    homepage:  https://github.com/craftypath/gotf/
    description: Handling multiple environments with Terraform made easy
    test: |
      system "#{bin}/gotf --version"
