name: CI

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: "1.14"

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install tools
        run: |
          ./setup.sh
          echo "::add-path::$(go env GOPATH)/bin"

      - name: Lint
        run: mage lint

      - name: Test
        run: mage test

      - name: Build
        if: "!startsWith(github.ref, 'refs/tags')"
        run: mage build

      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        run: mage release
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
